name: espin
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py39hb82d6ee_2
  - async_generator=1.10=py_0
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - binaryornot=0.4.4=py_1
  - black=21.5b2=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - bmi-topography=0.3.2=pyhd8ed1ab_0
  - bmipy=2.0=py_0
  - bokeh=2.3.2=py39hcbf5309_0
  - boost-cpp=1.74.0=h5b4e17d_4
  - brotlipy=0.7.0=py39hb82d6ee_1001
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2021.5.25=haa95532_1
  - cairo=1.16.0=hb19e0ff_1008
  - certifi=2021.5.30=py39haa95532_0
  - cffi=1.14.5=py39h0878f49_0
  - cfitsio=3.470=h0af3d06_7
  - cftime=1.5.0=py39h5d4886f_0
  - chardet=4.0.0=py39hcbf5309_1
  - child=21.03.12=h5362a0b_0
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorcet=2.0.6=pyhd8ed1ab_0
  - coverage=5.5=py39hb82d6ee_0
  - cryptography=3.4.7=py39hd8d06c1_0
  - curl=7.77.0=h789b8ee_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py39hb82d6ee_3
  - dask=2021.6.0=pyhd8ed1ab_0
  - dask-core=2021.6.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_1
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.12=pyh44b312d_0
  - distributed=2021.6.0=py39hcbf5309_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h39d44d4_0
  - fontconfig=2.13.1=h1989441_1005
  - freetype=2.10.4=h546665d_1
  - freexl=1.0.6=ha8e266a_0
  - fsspec=2021.6.0=pyhd8ed1ab_0
  - geos=3.9.1=h39d44d4_2
  - geotiff=1.6.0=ha8a8a2d_6
  - gettext=0.19.8.1=h1a89ca6_1005
  - gimli.units=0.2.1=py39h5d4886f_2
  - hdf4=4.2.15=h0e5069d_3
  - hdf5=1.10.6=nompi_h5268f04_1114
  - heapdict=1.0.1=py_0
  - holoviews=1.14.4=pyhd8ed1ab_0
  - hydrotrend=3.1.4=h5362a0b_0
  - icu=68.1=h0e60522_0
  - idna=2.10=pyh9f0ad1d_0
  - imageio=2.9.0=py_0
  - importlib-metadata=4.5.0=py39hcbf5309_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - intel-openmp=2021.2.0=h57928b3_616
  - ipykernel=5.5.5=py39h832f523_0
  - ipython=7.24.1=py39h832f523_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jbig=2.1=h8d14728_2003
  - jedi=0.18.0=py39hcbf5309_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jpeg=9d=h8ffe710_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py39hcbf5309_6
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py39hcbf5309_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - kealib=1.4.14=h96bfa42_2
  - kiwisolver=1.3.1=py39h2e07f2f_1
  - krb5=1.19.1=hbae68bd_0
  - landlab=2.3.0=py39h5d4886f_0
  - lcms2=2.12=h2a16943_0
  - lerc=2.2.1=h0e60522_0
  - libblas=3.9.0=9_mkl
  - libcblas=3.9.0=9_mkl
  - libclang=11.1.0=default_h5c34c98_1
  - libcurl=7.77.0=h789b8ee_0
  - libdeflate=1.7=h8ffe710_5
  - libffi=3.3=h0e60522_2
  - libgdal=3.2.2=h2c2ceef_6
  - libglib=2.68.2=h1e62bf3_2
  - libiconv=1.16=he774522_0
  - libkml=1.3.0=h9859afa_1013
  - liblapack=3.9.0=9_mkl
  - libnetcdf=4.8.0=nompi_hf689e7d_103
  - libpng=1.6.37=h1d00b33_2
  - libpq=13.3=hfcc5ef8_0
  - librttopo=1.1.0=hb340de5_6
  - libsodium=1.0.18=h8d14728_1
  - libspatialite=5.0.1=h762a7f4_5
  - libssh2=1.9.0=h680486a_6
  - libtiff=4.3.0=h0c97f57_1
  - libwebp-base=1.2.0=h8ffe710_2
  - libxml2=2.9.12=hf5bbc77_0
  - libzip=1.7.3=hfed4ece_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h8ffe710_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=2.0.1=py39hb82d6ee_0
  - matplotlib-base=3.4.2=py39h581301d_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py39hb82d6ee_1003
  - mkl=2021.2.0=hb70f87d_389
  - mkl-service=2.3.0=py39h2bbff1b_1
  - mkl_fft=1.3.0=py39h277e83a_2
  - mkl_random=1.2.1=py39hf11a4ad_2
  - model_metadata=0.7.0=pyh9f0ad1d_0
  - more-itertools=8.8.0=pyhd8ed1ab_0
  - msgpack-python=1.0.2=py39h2e07f2f_1
  - msys2-conda-epoch=20160418=1
  - mypy_extensions=0.4.3=py39hcbf5309_3
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py39hcbf5309_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - netcdf4=1.5.6=nompi_py39hc20e565_103
  - notebook=6.4.0=pyha770c72_0
  - numpy=1.20.2=py39ha4e8547_0
  - numpy-base=1.20.2=py39hc2deb75_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1k=h2bbff1b_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.4=py39h2e25243_0
  - pandoc=2.14.0.1=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - panel=0.11.3=pyhd8ed1ab_0
  - param=1.10.1=pyhd3deb0d_0
  - parso=0.8.2=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pathspec=0.8.1=pyhd3deb0d_0
  - patsy=0.5.1=py_0
  - pcre=8.44=ha925a31_0
  - permamodel=0.1.6=pyh9f0ad1d_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.2.0=py39h1a9d4f7_1
  - pip=21.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - pluggy=0.13.1=py39hcbf5309_4
  - poppler=21.03.0=h9ff6ed8_0
  - poppler-data=0.4.10=0
  - postgresql=13.3=h1c22c4f_0
  - proj=8.0.1=h1cfcee9_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - prompt_toolkit=3.0.18=hd8ed1ab_0
  - psutil=5.8.0=py39hb82d6ee_1
  - py=1.10.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pygments=2.9.0=pyhd8ed1ab_0
  - pymt=1.3.1=py39h5d4886f_0
  - pymt_child=0.2.1=py39h66837cb_0
  - pymt_hydrotrend=0.2.2=py39hb0a1f21_0
  - pymt_permamodel=0.1.3=py_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py39hcbf5309_7
  - pyqt-impl=5.12.3=py39h415ef7b_7
  - pyqt5-sip=4.19.18=py39h415ef7b_7
  - pyqtchart=5.12=py39h415ef7b_7
  - pyqtwebengine=5.12.1=py39h415ef7b_7
  - pyrsistent=0.17.3=py39hb82d6ee_2
  - pyshp=2.1.3=pyh44b312d_0
  - pysocks=1.7.1=py39hcbf5309_3
  - pytest=6.2.4=py39hcbf5309_0
  - python=3.9.4=h7840368_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=1_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - pyviz_comms=2.0.2=pyhd8ed1ab_0
  - pywin32=300=py39hb82d6ee_0
  - pywinpty=1.1.1=py39h99910a6_0
  - pyyaml=5.4.1=py39hb82d6ee_0
  - pyzmq=22.1.0=py39he46f08e_0
  - qt=5.12.9=h5909a2a_4
  - qtconsole=5.1.0=pyhd8ed1ab_0
  - qtpy=1.9.0=py_0
  - rasterio=1.2.4=py39hb4f844e_3
  - regex=2021.4.4=py39hb82d6ee_0
  - requests=2.25.1=pyhd3deb0d_0
  - scipy=1.6.3=py39hc0c34ad_0
  - scripting=0.2.4=py_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py39hcbf5309_3
  - shapely=1.7.1=py39haadaec5_5
  - six=1.16.0=pyh6c4a22f_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.35.5=h8ffe710_0
  - statsmodels=0.12.2=py39h5d4886f_0
  - tbb=2021.2.0=h2d74725_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - terminado=0.10.0=py39hcbf5309_0
  - terrainbento=2.0.0=pyh9f0ad1d_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tiledb=2.2.9=h78dabda_1
  - tk=8.6.10=h8ffe710_1
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py39hb82d6ee_1
  - tqdm=4.61.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - typed-ast=1.4.3=py39hb82d6ee_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - tzdata=2021a=he74cb21_0
  - udunits2=2.2.27.27=he38c35c_1
  - urllib3=1.26.5=pyhd8ed1ab_0
  - vc=14.2=hb210afc_4
  - vs2015_runtime=14.28.29325=h5e1d092_4
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py39hcbf5309_4
  - win_inet_pton=1.1.0=py39hcbf5309_2
  - wincertstore=0.2=py39hcbf5309_1006
  - winpty=0.4.3=4
  - wrapt=1.12.1=py39hb82d6ee_3
  - xarray=0.18.2=pyhd8ed1ab_0
  - xerces-c=3.2.3=h0e60522_2
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=h0e60522_0
  - zict=2.0.0=py_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.5.0=h6255e5f_0
  - pip:
    - tdqm==0.0.1
prefix: C:\Users\erb2734\Anaconda3\envs\espin
